apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-adgz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-adgz@sha256:f5139a90b0188e33705a0caa4e9b3be24a76bea4143655283d381cdbfee27639
        name: my-python
        resources: {}
status: {}
